const ideas = [
    "Stargazing in the backyard", "Homemade pizza night", "Sunset hike",
    "Build a blanket fort and watch a movie", "Board game challenge",
    "Visit a free museum", "Couples yoga at home", "Karaoke in your living room",
    "Dance in the kitchen", "Cook a new cuisine together", "Night drive & ice cream",
    "Plan your dream vacation", "Read poetry to each other", "Write love notes",
    "Make a scrapbook", "Do a puzzle together", "Watch old home videos",
    "Make a playlist together", "Photo scavenger hunt", "Picnic at the park",
    "Bike ride and smoothies", "Visit a farmers market", "Draw portraits of each other",
    "Make homemade candles", "Have a chocolate tasting night", "Learn a TikTok dance",
    "Write a short story together", "Backyard camping", "Paint and sip night",
    "Read a book aloud", "Take a personality quiz together", "Make a time capsule",
    "Try a food neither of you has had", "Volunteer together", "Window shop downtown",
    "Visit a botanical garden", "Bake a fancy dessert", "Take funny photobooth pics",
    "Watch a foreign film", "Make a vision board", "Play truth or dare", "Do face masks",
    "Create a cocktail or mocktail recipe", "Slow dance to a record", "Take a scenic drive",
    "Plan a themed dinner night", "Decorate mugs together", "DIY tie-dye shirts",
    "Recreate your first date", "Play mini golf", "Do a YouTube workout together", "write a bucket list", "have a cook-off", "make your own movie", "build a LEGO set",
    "watch a documentary", "do a blind taste test", "do couples trivia", "watch the sunrise",
    "feed ducks at the pond", "make shadow puppets", "practice accents", "pretend you're tourists",
    "do a fashion show", "make a dream board", "binge nostalgic cartoons", "play card games in candlelight",
    "play hide and seek at night", "visit a dog park", "decorate cupcakes", "go people watching",
    "bake breakfast for dinner", "make origami", "do karaoke carpool", "tour open houses for fun",
    "invent a holiday and celebrate it", "write a song together", "make a time capsule", "Build a cozy reading nook and read to each other", "Recreate a dish from your favorite restaurant",
  "Take Polaroid selfies around town", "Make a “relationship timeline” on a poster board",
  "Decorate pillowcases with fabric markers", "Try out a random recipe generator and cook it",
  "Watch a childhood favorite movie and rate it", "Make each other paper crowns and wear them to dinner",
  "Hand-make a couples crossword puzzle", "Walk through a neighborhood and “house shop”",
  "Go to the library and pick books for each other", "Roast marshmallows over a candle",
  "Write each other short poems and frame them", "Go to a dollar store and build gift bags for each other",
  "Film a “Day in the Life” vlog", "Watch your zodiac compatibility on YouTube",
  "Make friendship bracelets", "Trade playlists and listen together",
  "Try on outfits from each other’s closet", "Build your dream house on paper or in Minecraft",
  "Write a joint bucket list and hang it up", "Look up constellation myths and stargaze",
  "Try a random dance tutorial online", "Plan a fake vacation and build the itinerary",
  "Doodle your favorite memories of each other", "Make DIY candles with your own scents",
  "Host a “mini prom” at home with music and dressing up", "Play “Guess That Sound” with random household items",
  "Create clay sculptures of each other", "Make and decorate your own pizzas",
  "Design your couple logo or crest", "Look through baby photos and guess the story",
  "Each pick a favorite meme and explain it", "Listen to a romantic podcast episode",
  "Record your love story as a podcast", "Go on a themed thrift shop hunt (e.g., 90s style)",
  "Have a blindfolded taste test challenge", "Try latte art with warm milk and coffee",
  "Visit a local art exhibit and sketch your favorite piece", "Watch travel vlogs and pretend you're planning a trip",
  "Take a long detour walk without a destination", "Watch time-lapse nature videos while cuddling",
  "Each write a love haiku", "Learn to fold a specific origami animal together",
  "Write compliments on sticky notes and hide them around", "Find constellation shapes in random cloud formations",
  "Bake a single giant cookie to share", "Write fictional bios for each other like a character sheet",
  "Watch a silent film and narrate it yourselves", "Create your own 3-song relationship soundtrack”,
  "Visit an open mic night or poetry slam", "Take turns giving each other 5-minute massages",
  "Try a paint-by-numbers kit together", "Make your own fortune cookies with inside jokes",
  "Film a cooking show starring yourselves", "Host a tea party on the living room floor",
  "Take a walk and collect nature trinkets for a shadow box", "Decorate reusable grocery bags with fabric paint",
  "Watch a “bad” movie and give it a serious review", "Make a playlist themed around your future goals",
  "Research your zodiac moon signs and talk about it", "Give each other ridiculous fake interviews",
  "Go on a “yes” walk—say yes to whatever idea comes up", "Play charades with just romantic gestures",
  "Try drawing portraits with your non-dominant hands", "Build a cardboard castle or fort",
  "Go to a pet store just to look at cute animals", "Make a “dream fridge” Pinterest board",
  "Watch a YouTube cooking competition and vote on the winner", "Make each other a quiz like “How well do you know me?”",
  "Plan a themed night (e.g., Paris night, 90s night)", "Try finger painting on canvas or paper",
  "Go to a local thrift store and find a gift under $5", "Pick a YouTube channel and binge 3 random videos",
  "Create a mini scrapbook of your top 5 dates", "Go to the bookstore and each pick one book for the other",
  "Make breakfast in bed for dinner", "Try drawing one continuous line art of each other",
  "Give each other funny superlatives like “Most Likely to...”", "Make a list of your top 10 favorite things about each other",
  "Watch a documentary and share your thoughts after", "Do a memory challenge—name all your past dates",
  "Design a family crest or emblem together", "Play a cooperative video game or mobile app",
  "Have a “no electricity” night with candles and stories", "Try origami heart folding and leave them in random places",
  "Record voice messages to open in the future", "Plan a fake celebrity wedding for yourselves",
  "Take turns reading Wikipedia rabbit holes out loud", "Write a cheesy romance scene together",
  "Invent a new board game using stuff around the house", "Take a virtual museum or aquarium tour",
  "Try out a new accent and stick with it for 30 minutes", "Plan a themed snack board (charcuterie, dessert, etc.)",
  "Swap hobbies for an hour (draw if one of you writes, etc.)", "Have a contest to make the most creative sandwich",
  "Plan a surprise for your future selves", "Write a story using only emojis and then decode each other’s"
];
